// @components
import { Footer } from "@/components";

// @fonts
import localFont from "next/font/local";

// @types
import type { Metadata } from "next";

// @styles
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased py-20 bg-background overflow-x-hidden`}
      >
        <main className="min-h-screen relative">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
